insert into artist (dtype,name, description) values ('Band', 'Pink Floyd', 'A leading prog rock band hailing from England, Pink Floyd had a varied line up, perhaps most affected by the sad loss of Sid Barret to drugs')
insert into artist (dtype,name, description) values ('Band', 'Fairport Convention', 'The first band to do folk-rock in the UK, Fairport Convention shaped British music for a decade')
insert into artist (dtype,name, description) values ('Artist', 'Bob Dylan', 'Bob Dylan grew out of the US folk scene and was considered *Woodie Guthries* successor by many.  Famously he was involved in the civil rights movement, writing and singing protest songs.  At the *1965 Newport Folk Festival* Dylan *went electric*, heralding a new (and, in many critics eyes, lesser) period.  Famously, folk luminary, *Pete Seeger* stormed out.')
insert into artist (dtype,name, description) values ('Band', 'Led Zepplin', 'A British rock band of the 1970s')
insert into artist (dtype, name, description) values ('Artist', 'Ry Cooder', '*Ry Cooder* has had a very varied career.  He came to mainstream attention with the *Buena Vista Social Club* album, which lead to greater interest in Cuban music.  His latest album follows *Buddy*, a cat, travelling around the US')
insert into artist (dtype,name,description) values ('Artist', 'Richard Thompson', 'Voted one of the top 50 guitarists ever, *Richard Thompson* is one of the unsung stars of the last 30 years.  First playing with *Fairport Convention*, he then dueted with his wife *Linda*, splitting in the mid 80s.  Since then he has been recording and playing as a solo artist, sometimes with a backing band, and, more often than not, with the incomprable *Danny Thompson* on bass.')
insert into artist (dtype,name,description) values ('Band', 'Capercaillie', '*Capercaillie* were the first to take traditional and Celtic music and give it a *groove*.  Highly successful, the members are now pursuing side projects - both *Karen Mathieson* and *Mike McGoldrick* have solo albums out.')

insert into disc (name, artist_id, description) values ('Dark Side of the Moon', 1, 'The definitive Pink Floyd album')
insert into disc (name, artist_id, description) values ('Liege and Lief', 2, 'The *first* folk-rock album ever made in the UK, this was the only studio recording of the classic line up of *Sandy Denny*, *Richard Thompson*, *Dave Swarbick*, *Ashley Hutchings* and *Simon Nicol*')
insert into disc (name, artist_id) values ('The Wall', 1)
insert into disc (name, artist_id) values ('The Freewheelin Bob Dylan', 3)
insert into disc (name, artist_id, _release) values ('Blood on the Tracks', 3, '1975')
insert into disc (name, artist_id) values ('Desire', 3)
insert into disc (name, artist_id) values ('Led Zepplin 1', 4)
insert into disc (name, artist_id, description) values ('Buena Vista Social Club', 5, 'This album brough Cuban music to the attention of the world')
insert into disc (name, artist_id, description) values ('Chavez Ravine', 5, 'Written about *Ry Cooder* birthplace')
insert into disc (name, artist_id, _release, description) values ('My Name is Buddy', 5, '2007', 'Follows Buddy the Cat as he explores the USA')
insert into disc (name, artist_id,_release, description) values ('Mock Tudor', 6, 1999, 'A celebration of *Richard Thompsons* love of the suburbs and anonymity, *Mock Tudor* includes the classic tracks *Cooksferry Queen* and *Crawl Back*.' )
insert into disc (name, artist_id,_release, description) values ('Front Parlour Ballads', 6, 2005, '*Richard Thompsons first truly solo album.  Whilst not his most immediately accessible album, it grows on you over time.*')
insert into disc (name, artist_id,_release) values ('The Old Kit Bag', 6, 2003)
insert into disc (name, artist_id,_release) values ('Rumor and Sigh', 6, 1991)

insert into bandmember (name, band_id) values ('Syd Barett', 1)
insert into bandmember (name, band_id) values ('David Gilmor', 1)
insert into bandmember (name, band_id) values ('Roger Waters', 1)
insert into bandmember (name, band_id) values ('Richard Thompson', 2)
insert into bandmember (name, band_id) values ('Sandy Denny', 2)
insert into bandmember (name, band_id) values ('Dave Pegg', 2)
insert into bandmember (name, band_id) values ('Ashley Hutchings', 2)
insert into bandmember (name, band_id) values ('Simon Nicol', 2)
insert into bandmember (name, band_id) values ('Dave Swarbick', 2)
insert into bandmember (name, band_id) values ('Rick Sanders', 2)
insert into bandmember (name, band_id) values ('Chris Leslie', 2)
insert into bandmember (name, band_id) values ('Maart Alcock', 2)
insert into bandmember (name, band_id) values ('Karen Mathieson', 7)
insert into bandmember (name, band_id) values ('Mike McGoldrick', 7)
insert into bandmember (name, band_id) values ('Charlie', 7)

insert into user (username, password) values ('administrator', 'administrator')
