package Permissions;

dialect 'mvel'

import org.jboss.seam.security.permission.PermissionCheck;
import org.picketlink.idm.api.Role;
import org.picketlink.idm.api.User;
import org.picketlink.idm.api.Group;

rule IsDemoUser
  no-loop
  activation-group "permissions"
when
  check: PermissionCheck(resource == "foo", permission == "execute", granted == false)
  User(id == "demo")
then
  check.grant();
end

rule IsInUserGroup
  no-loop
  activation-group "permissions"
when
  check: PermissionCheck(resource == "bar", permission == "execute", granted == false)
  Group(name == "USERS")
then
  check.grant();
end
