insert into customer (username, password, name) values ('pete', 'edinburgh', 'Pete Muir')
insert into customer (username, password, name) values ('dan', 'laurel', 'Dan Allen')
insert into customer (username, password, name) values ('lincoln', 'charlotte', 'Lincoln Baxter III')
insert into customer (username, password, name) values ('shane', 'brisbane', 'Shane Bryzak')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (1, 129, 3, 'Marriott Courtyard', 'Tower Place, Buckhead', 'Atlanta', 'GA', '30305', 'USA')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (2, 84, 4, 'Doubletree Atlanta-Buckhead', '3342 Peachtree Road NE', 'Atlanta', 'GA', '30326', 'USA')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (3, 289, 4, 'W New York - Union Square', '201 Park Avenue South', 'New York', 'NY', '10003', 'USA')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (4, 219, 3, 'W New York', '541 Lexington Avenue', 'New York', 'NY', '10022', 'USA')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (5, 250, 3, 'Hotel Rouge', '1315 16th Street NW', 'Washington', 'DC', '20036', 'USA')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (6, 159, 4, '70 Park Avenue Hotel', '70 Park Avenue, 38th St', 'New York', 'NY', '10016', 'USA')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (7, 198, 4, 'Parc 55', '55 Cyril Magnin Street', 'San Francisco', 'CA', '94102', 'USA')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (8, 189, 4, 'Conrad Miami', '1395 Brickell Ave', 'Miami', 'FL', '33131', 'USA')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (9, 111, 4, 'Grand Hyatt', '345 Stockton Street', 'San Francisco', 'CA', '94108', 'USA')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (10, 54, 1, 'Super 8 Eau Claire Campus Area', '1151 W MacArthur Ave', 'Eau Claire', 'WI', '54701', 'USA')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (11, 199, 4, 'San Francisco Marriott', '55 Fourth Street', 'San Francisco', 'CA', '94103', 'USA')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (12, 543, 4, 'Hilton Diagonal Mar', 'Passeig del Taulat 262-264', 'Barcelona', 'Catalunya', '08019', 'ES')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (13, 335, 5, 'Hilton Tel Aviv', 'Independence Park', 'Tel Aviv', '', '63405', 'IL')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (14, 242, 5, 'InterContinental Hotel Tokyo Bay', '1-15-2 Kaigan', 'Tokyo', 'Minato', '105', 'JP')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (15, 130, 4, 'Hotel Beaulac', ' Esplanade Léopold-Robert 2', 'Neuchatel', '', '2000', 'CH')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (16, 266, 5, 'Conrad Treasury Place', '130 William Street', 'Brisbane', 'QL', '4001', 'AU')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (17, 170, 4, 'Ritz-Carlton Montreal', '1228 Sherbrooke St West', 'Montreal', 'Quebec', 'H3G1H6', 'CA')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (18, 179, 4, 'Ritz-Carlton Atlanta', '181 Peachtree St NE', 'Atlanta', 'GA', '30303', 'USA')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (19, 145, 4, 'Swissotel Sydney', '68 Market Street', 'Sydney', 'NSW', '2000', 'AU')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (20, 178, 4, 'Meliá White House', 'Albany Street Regents Park', 'London', '', 'NW13UP', 'GB')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (21, 159, 3, 'Hotel Allegro', '171 W Randolph Street', 'Chicago', 'IL', '60601', 'USA')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (22, 296, 5, 'Caesars Palace', '3570 Las Vegas Blvd S', 'Las Vegas', 'NV', '89109', 'USA')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (23, 300, 4, 'Mandalay Bay Resort & Casino', '3950 Las Vegas Blvd S', 'Las Vegas', 'NV', '89119', 'USA')
insert into hotel (id, price, stars, name, address, city, state, zip, country) values (24, 100, 2, 'Hotel Cammerpoorte', 'Nationalestraat 38-40', 'Antwerp', '', '2000', 'BE')
