insert into Contact ( firstName, lastName, cellPhone, address, city, state, zip, country, version ) values ( 'Gavin', 'King', null, 'Peachtree Rd', 'Atlanta', 'GA', '30305', 'USA', 1 )
insert into Contact ( firstName, lastName, cellPhone, address, city, state, zip, country, version ) values ( 'Norman', 'Richards', null, null, 'Austin', 'TX', '78701', 'USA', 1 )
insert into Contact ( firstName, lastName, cellPhone, address, city, state, zip, country, version ) values ( 'Shane', 'Bryzak', null, null, 'Brisbane', 'QLD', null, 'Australia', 1 )
insert into Contact ( firstName, lastName, cellPhone, address, city, state, zip, country, version ) values ( 'Pete', 'Muir', null, null, 'Edinburgh', 'Scotland', null, 'UK', 1 )
insert into Contact ( firstName, lastName, cellPhone, address, city, state, zip, country, version ) values ( 'Michael', 'Yuan', null, null, 'Austin', 'TX', '78701', 'USA', 1 )
insert into Contact ( firstName, lastName, cellPhone, address, city, state, zip, country, version ) values ( 'Steve', 'Ebersole', null, null, 'Austin', 'TX', '78701', 'USA', 1 )
insert into Contact ( firstName, lastName, cellPhone, address, city, state, zip, country, version ) values ( 'Christian', 'Bauer', null, null, 'Zurich', null, null, 'Switzerland', 1 )
insert into Contact ( firstName, lastName, cellPhone, address, city, state, zip, country, version ) values ( 'Max', 'Andersen', null, null, 'Neuchatel', null, null, 'Switzerland', 1 )
insert into Contact ( firstName, lastName, cellPhone, address, city, state, zip, country, version ) values ( 'Emmanuel', 'Bernard', null, null, 'Atlanta', 'GA', null, 'USA', 1 )
insert into Contact ( firstName, lastName, cellPhone, address, city, state, zip, country, version ) values ( 'Michael', 'Youngstrom', null, null, 'Salt Lake City', 'UT', null, 'USA', 1 )
insert into Contact ( firstName, lastName, cellPhone, address, city, state, zip, country, version ) values ( 'Jacob', 'Hookom', null, null, 'Minneapolis', 'MN', null, 'USA', 1 )
insert into Contact ( firstName, lastName, cellPhone, address, city, state, zip, country, version ) values ( 'Dan', 'Allen', null, null, 'Laurel', 'MD', 20724, 'USA', 1 )
